PROJECT_ROOT = "/home/kivihen/src/uz3eg_iocc_base_2024_2"

WORK_ROOT = PROJECT_ROOT + "/build/tmp/work/cortexa72-cortexa53-xilinx-linux"

YOCTO_PYTHON_PACKAGE_COPY_DESTINATION = "/home/kivihen/src/Package Comparisons"

YOCTO_PYTHON_PACKAGE_COPY_DESTINATION_SUFFIX_PY = " PY"
YOCTO_PYTHON_PACKAGE_COPY_DESTINATION_SUFFIX_PYC = " PYC"
YOCTO_PYTHON_PACKAGE_COPY_DESTINATION_SUFFIX_PYC_OPT = " PYC OPT"